build: false

environment:
    PYTHON: "C:\\Python27-x64"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "python setup.py install"
  - "%PYTHON%/Scripts/pip.exe install nose"
  - "%PYTHON%/Scripts/pip.exe install coverage"

test_script:
  - dir
  - cd phreeqpython
  - dir
  - cd lib
  - dir
  - "%PYTHON%/Scripts/nosetests"
